# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Precision and Recall Graphs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Precision and Recall Graphs
	pod 'Charts'
end
